name: unittests

on: [ push, pull_request ]

jobs:
  unittests:
    name: '[PHP ${{ matrix.php-version }} | Flow ${{ matrix.flow-version }}] Unit Tests'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version: [ 8.2, 8.3 ]
        flow-version: [ '8.3', '9.0.0-beta' ]

    env:
      APP_ENV: true
      FLOW_CONTEXT: Testing/Unit
      FLOW_DIST_FOLDER: flow-base-distribution

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, xml, json, zlib, iconv, intl, pdo_sqlite
          ini-values: opcache.fast_shutdown=0

      - name: "Create composer project - No install"
        run: composer create-project neos/flow-base-distribution ${{ env.FLOW_DIST_FOLDER }} --prefer-dist --no-progress --no-install "^${{ matrix.flow-version }}"

      - name: "Allow neos composer plugin"
        run: composer config --no-plugins allow-plugins.neos/composer-plugin true
        working-directory: ${{ env.FLOW_DIST_FOLDER }}

      - name: "Create composer project  - Require behat in compatible version"
        run: composer require --dev --no-update "neos/behat:@dev"
        working-directory: ${{ env.FLOW_DIST_FOLDER }}

      - name: "Create composer project - Install project"
        run: composer install
        working-directory: ${{ env.FLOW_DIST_FOLDER }}

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ${{ env.FLOW_DIST_FOLDER }}/DistributionPackages/Netlogix.Eel.JavaScript

      - name: Install netlogix/eel-javascript
        run: composer require netlogix/eel-javascript:@dev
        working-directory: ${{ env.FLOW_DIST_FOLDER }}

      - name: Run tests
        run: bin/phpunit -c DistributionPackages/Netlogix.Eel.JavaScript/Tests/phpunit.xml.dist --testsuite="Unit" --bootstrap "Build/BuildEssentials/PhpUnit/UnitTestBootstrap.php"
        working-directory: ${{ env.FLOW_DIST_FOLDER }}
